#!/bin/bash

filename=$1

get_primes() {
    local args=("$@")
    local len=${#args[@]}

    local num=${args[0]//:/'='}
    local primes=("${args[@]:2}")

    IFS="*"
    local factors="${primes[*]}"
    IFS=" "

    echo "$num$factors"
}

while read -r number; do
    output=$(factor "$number")
    read -ra factors <<< "$output"
    echo "$(get_primes "${factors[@]}")"
done < "$filename"

