#!/usr/bin/python3
import math
import sys



def factorize_numbers(file_path):
    with open(file_path, 'r') as file:
        numbers = file.readlines()
        for number in numbers:
            n = int(number)
            factors = []
            if n % 2 == 0:
                factors.append((n // 2, 2))
                continue
            for i in range(3, math.isqrt(n) + 2):
                if n % i == 0:
                    factors.append((n // i, i))
                    break  # Stop the loop after finding a factor
            if factors:
                print(f"{n} = {' '.join([f'{p}*{q}' for p, q in factors])}")
            else:
                print(f"{n} is a prime number")

args = sys.argv
if len(args) < 2:
    print("usage factors filename.txt")
factorize_numbers(args[1])
