#!/usr/bin/python3
import sys
import subprocess


with open(sys.argv[1], 'r') as file:
    numbers = file.read().splitlines()
for number in numbers:
    result = subprocess.run(['factor', number], capture_output=True, text=True)
    factors = result.stdout.strip().split()[1:]
    factors_str = '*'.join(factors)
    output = f"{number}={factors_str}"
    print(output)
