#!/bin/bash

filename=$1

while read -r number; do
    factors=$(factor "$number" | awk '{ for(i=2;i<=NF;i++) { printf "%s%s",sep,$i; sep="*"} printf "\n" }')
    echo "$number=$factors"
done < "$filename"
